- name: Install frequently used packages with brew
  become_user: "{{ normal_user }}"
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name: git,tig,python@3.8,node,golang,todo-txt
